dist: xenial
language: node_js
node_js:
  - 12

addons:
  sonarcloud:
    organization: jspwiki-fixers
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=samhareem_jspwiki

notifications:
  email: false
